els-ASAP auto commit file/tag ypbind-1.37.1-9.el7.src.rpm

diff --git a/ypbind-pre-setdomain b/ypbind-pre-setdomain
--- a/ypbind-pre-setdomain
+++ b/ypbind-pre-setdomain
@@ -9,22 +9,30 @@
 
 OTHER_YPBIND_OPTS=""
 
+TIMEOUT=5
 DOMAINNAME=`domainname`
 if [ "$DOMAINNAME" = "(none)" -o "$DOMAINNAME" = "" ]; then
     echo -n $"Setting NIS domain: "
+    seconds=0
+    while [ $seconds -lt $TIMEOUT ]; do
     if [ -n "$NISDOMAIN" ]; then
-	domainname $NISDOMAIN
-	echo $"'$NISDOMAIN' (environment variable)"
+        domainname $NISDOMAIN
+        echo $"'$NISDOMAIN' (environment variable)"
+        break
     else # See if the domain is set in config file
-	NISDOMAIN=`awk '{ if ($1 == "domain") {print $2; exit} }' /etc/yp.conf`
-	if [ -n "$NISDOMAIN" ]; then
-	    domainname $NISDOMAIN
-	    echo $"'$NISDOMAIN' (/etc/yp.conf)"
-	else
-            logger -t ypbind $"domain not found"
-            exit 1
+        NISDOMAIN=`awk '{ if ($1 == "domain") {print $2; exit} }' /etc/yp.conf`
+        if [ -n "$NISDOMAIN" ]; then
+            domainname $NISDOMAIN
+            echo $"'$NISDOMAIN' (/etc/yp.conf)"
+            break
+        else
+            seconds=$(($seconds+1))
+            sleep 1
         fi
     fi
+    done
+    # Give up if NISDOMAIN is still not set
+    [ -z "$NISDOMAIN" ] && logger -t ypbind $"domain not found" && exit 1
 fi
 
 #/etc/rpc check
